### PR TITLE
🚧Add switches to toggle protocols

### PR DESCRIPTION
**Pull request by MattPoblete**

### CODE REVIEW

**Review by esteblock — CHANGES_REQUESTED** [review]
Hello @MattPoblete 
Where as an admin I can define what protocols the users will be exposed on each network?
Can you please write documentation about this in the README

**Comment by MattPoblete** [comment]
Protocols sholud be defined by network.
Mainnet:
 - [ ] Soroswap
 - [ ] SDEX
Testnet:
 - [ ] Soroswap
 - [ ] Phoenix

**Comment by MattPoblete** [comment]
image
Github workflow randomly failing navigation tests but they are passing in local instance & manual testing

**Comment by MattPoblete** [comment]
image
workflow approved!

**Comment by MattPoblete** [comment]
> @esteblock I will test frontend tests `yar ci run`

please run: yarn cy:run

**Pull request merged**
